### ISSUE TITLE
Error installing 'atlantis-supervisor' deb in supervisor docker container

### ISSUE THREAD

**Issue by budhrg** [ooyala/atlantis-supervisor#56]
I have aquarium setup in my vagrant locally with all running components.

After pulling latest changes from `master` branch and installing `supervisor` deb in `supervisor container`, I am getting following error:
```
root@8beb78fb3715:~# dpkg -i atlantis-supervisor_0.1.0_amd64.deb 
(Reading database ... 17345 files and directories currently installed.)
Preparing to unpack atlantis-supervisor_0.1.0_amd64.deb ...
Unpacking atlantis-supervisor (0.1.0) over (0.1.0) ...
dpkg: dependency problems prevent configuration of atlantis-supervisor:
 atlantis-supervisor depends on software-properties-common; however:
  Package software-properties-common is not installed.

dpkg: error processing package atlantis-supervisor (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 atlantis-supervisor
```

It looks like `software-properties-common` installation fails. Also, unable to install it manually due to unmet dependencies.

Also, is it possible that this issue might have occurred due to using `trusty` instead of `precise` as base image?
Any opinion?

**Comment by edanaher** [comment]
We're still on precise; trusty may have some issues.  However, the snippet you posted doesn't indicate that `software-properties-common` _failed_; it just means that it's not installed.  dpkg doesn't do any dependency handling, so it will just fall over if anything is missing.

Try `apt-get install -f` to fix broken dependencies; if that doesn't work, try `apt-get install software-properties-common`.  I'd expect that to work, since the package [does exist](http://packages.ubuntu.com/trusty/admin/software-properties-common) in trusty.

**Comment by budhrg** [comment]
Using `precise` fixed it.
